name:                TextGameInterpreter
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/TextGameInterpreter#readme
license:             BSD3
author:              Ewa Pasterz
maintainer:          example@example.com
copyright:           2022 Ewa Pasterz
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - split
  - parsec >= 3.1.14.0
  - text
  - containers

executables:
  TextGameInterpreter:
    source-dirs:      src
    main:             Main.hs
